apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${CI_PROJECT_NAME}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${CI_PROJECT_NAME}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ${CI_PROJECT_NAME}
    spec:
      containers:
        - image: ${IMAGE_TAG}
          imagePullPolicy: Always
          name: ${CI_PROJECT_NAME}
          ports:
            - containerPort: 8080 
      imagePullSecrets:
        - name: regcred
