name: Build and Publish

env:
  CI_PROJECT_NAME: run-aspnetcore-microservices 
  IMAGE_TAG: "ghcr.io/rmvekb/aspnetrunbasics:latest"

on:
  # run it on push to the default repository branch
  push:
    branches: ['**']
  # run it during pull request
  pull_request:

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: self-hosted
    # steps to perform in job
    steps:
    
      - name: Login to Github Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: rmvekb
          password: ${{ secrets.KEY_TOKEN }}
    
      - uses: actions/checkout@v3
      - name: Build the stack
        working-directory: ./src
        run: |
          docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d --build
          docker-compose push
          envsubst < deployment.yaml > deployment.k8s.yaml
          cat deployment.k8s.yaml
###
