name: Build and Publish

on:
  # run it on push to the default repository branch
  push:
    branches: ['**']
  # run it during pull request
  pull_request:

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: self-hosted
    # steps to perform in job
    steps:
      
      - uses: actions/checkout@v3
      - name: Build the stack
        run: docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d --build
